cache:
  paths:
    - node_modules/

stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: node:latest
  script:
    - echo "Building..."
    - npm run build-server
    - npm run build-client
  only:
    - merge_requests

test:
  stage: test
  image: node:latest
  script:
    - npm install
    - echo "Testing client..."
    - npm run build-test-client
    - echo "Testing server..."
    - npm run build-test-server
  only:
    - merge_requests

deploy:
  stage: deploy
  image: node:latest
  script:
    - echo "Deploying..."
    - cd client
    - npx vercel --token $VERCEL_TOKEN --confirm=n --prod
  only:
    - main
  variables:
    VERCEL_TOKEN: $VERCEL_TOKEN
